/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nypodev;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static nypodev.Kullanici.k;
import static nypodev.Kullanici.kullanicilar;

/**
 *
 * @author DELL
 */
public class kullaniciGiris extends javax.swing.JFrame {
    static String mail;
    static String sifre;

    /**
     * Creates new form kullaniciGiris
     */
    public kullaniciGiris() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        giris = new javax.swing.JButton();
        kullaniciMail = new javax.swing.JTextField();
        kullaniciSifre = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        kayitol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("E-mail");

        giris.setText("Giriş");
        giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisActionPerformed(evt);
            }
        });

        kullaniciMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciMailActionPerformed(evt);
            }
        });

        jLabel2.setText("Şifre");

        kayitol.setText("Kayıt Ol");
        kayitol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(giris)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(kayitol))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kullaniciMail, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(kullaniciSifre))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kullaniciMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giris)
                    .addComponent(kayitol))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisActionPerformed
        // TODO add your handling code here:
        
        mail = String.valueOf(kullaniciMail.getText());
        sifre = String.valueOf(kullaniciSifre.getText());
       
        File f = new File("/Users/beyzanursaritas/Downloads/proje/Musteri.txt");
        
        int i;
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(f))); // txt'den okuma yapmak için gereken kod.
        } catch (FileNotFoundException ex) {
            Logger.getLogger(kullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            while((k = reader.readLine()) != null ){                                                          // txt içindeki veriyi kullanicilar adlı bir arrayList içine ekliyor.
                kullanicilar.add(k);
            }
        } catch (IOException ex) {
            Logger.getLogger(kullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        boolean hata = false;
        for(int j = 0 ; j<kullanicilar.size() ; j++){       // Kullanıcı adı ve şifre onaylayan kod.
            
         String temp[] = kullanicilar.get(j).split(";");

            if(mail.equalsIgnoreCase(temp[5]) && sifre.equalsIgnoreCase(temp[2]) ){

                System.out.println("Başarılı Giriş");
                NYPODEV.urun.setVisible(true);
                NYPODEV.giris.setVisible(false);// eğer GUI ortamında yaparsan yani başarılı giriş olduğunda başka bir formun açılmasını istiyorsan bunu kullanmalısın
                hata = true;
            }
           
        }
        
        if(hata == false) {
            JOptionPane.showMessageDialog(null,"Kullanıcı adı veya şifre hatalı.");
        }
    }//GEN-LAST:event_girisActionPerformed

    private void kayitolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitolActionPerformed
                
                NYPODEV.giris.setVisible(false);
                NYPODEV.kaydol.setVisible(true);
        
    }//GEN-LAST:event_kayitolActionPerformed

    private void kullaniciMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullaniciMailActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton giris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kayitol;
    private javax.swing.JTextField kullaniciMail;
    private javax.swing.JPasswordField kullaniciSifre;
    // End of variables declaration//GEN-END:variables
}
