/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nypodev;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import static nypodev.SiparisIstegi.s;
import static nypodev.SiparisIstegi.siparisIstekleri;
import static nypodev.Urunler1.a;
import static nypodev.Urunler1.b;
import static nypodev.Urunler1.c;
import static nypodev.siparisler.temp;

/**
 *
 * @author DELL
 */
public class onaylananSiparisler extends javax.swing.JFrame {

    static String temp[];
    static String temp1[];
    static String temp2[];
    File f = new File("/Users/beyzanursaritas/Downloads/proje/Siparisler.txt");
    public onaylananSiparisler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siparis1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        siparis2 = new javax.swing.JTextField();
        siparis3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        siparis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparis1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Onaylanan Siparisler:");

        jButton1.setText("Onaylanan Siparisleri Goster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Geri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(siparis2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siparis1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siparis3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(37, 37, 37)
                .addComponent(siparis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(siparis2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(siparis3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siparis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siparis1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int i;
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(f))); // txt'den okuma yapmak için gereken kod.
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Urunler1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            while((s = reader.readLine()) != null ){                                                          // txt içindeki veriyi kullanicilar adlı bir arrayList içine ekliyor.
                siparisIstekleri.add(s);
            }
        } catch (IOException ex) {
            Logger.getLogger(Urunler1.class.getName()).log(Level.SEVERE, null, ex);
        }

            temp= siparisIstekleri.get(0).split(";");        
            siparis1.setText(temp[4]+" nolu müşterinin siparişi toplam  =  "+temp[3]+" TL");

            
            temp1= siparisIstekleri.get(1).split(";");
            siparis2.setText(temp1[4]+" nolu müşterinin siparişi toplam  =  "+temp1[3]+" TL");
            
        
           
            temp2= siparisIstekleri.get(2).split(";");
            siparis3.setText(temp2[4]+" nolu müşterinin siparişi toplam  =  "+temp2[4]+" TL");
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NYPODEV.onaylananSiparisler.setVisible(false);
        NYPODEV.siparisler.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField siparis1;
    private javax.swing.JTextField siparis2;
    private javax.swing.JTextField siparis3;
    // End of variables declaration//GEN-END:variables
}
