/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nypodev;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static nypodev.SiparisIstegi.s;
import static nypodev.SiparisIstegi.siparisIstekleri;



/**
 *
 * @author DELL
 */
public class siparisler extends javax.swing.JFrame {
     public static String a;
    public static String b;
    public static String c;
    static String temp[];
    static String temp1[];
    static String temp2[];
    static String siparisno="0";
    File f = new File("/Users/beyzanursaritas/Downloads/proje/Siparis_istegi.txt");
     public  void main(String[] args) {

        int i;
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(f))); // txt'den okuma yapmak için gereken kod.
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Urunler1.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
        try {
            while((s = reader.readLine()) != null ){                                                          // txt içindeki veriyi kullanicilar adlı bir arrayList içine ekliyor.
                siparisIstekleri.add(s);
            }
        } catch (IOException ex) {
            Logger.getLogger(Urunler1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    public siparisler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        urunSepet1 = new javax.swing.JTextField();
        urunSepet2 = new javax.swing.JTextField();
        urunSepet3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Onaylanan Siparişler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        urunSepet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunSepet1ActionPerformed(evt);
            }
        });

        urunSepet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunSepet2ActionPerformed(evt);
            }
        });

        urunSepet3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunSepet3ActionPerformed(evt);
            }
        });

        jLabel1.setText("1.Sipariş");

        jLabel2.setText("2. Sipariş");

        jLabel3.setText("3. Sipariş");

        jButton3.setText("Siparişleri Göster");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Onayla");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Onayla");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Onayla");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setText("Geri");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urunSepet2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urunSepet1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urunSepet3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton7)
                            .addComponent(jButton3)
                            .addComponent(jButton6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jButton4)
                    .addContainerGap(281, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urunSepet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(urunSepet2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(urunSepet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jButton4)
                    .addContainerGap(276, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void urunSepet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunSepet1ActionPerformed
        urunSepet1.setText(a);
      
    }//GEN-LAST:event_urunSepet1ActionPerformed

    private void urunSepet2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunSepet2ActionPerformed
        urunSepet2.setText(b);
    }//GEN-LAST:event_urunSepet2ActionPerformed

    private void urunSepet3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunSepet3ActionPerformed
        urunSepet2.setText(c);
    }//GEN-LAST:event_urunSepet3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i;
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(f))); // txt'den okuma yapmak için gereken kod.
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Urunler1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            while((s = reader.readLine()) != null ){                                                          // txt içindeki veriyi kullanicilar adlı bir arrayList içine ekliyor.
                siparisIstekleri.add(s);
            }
        } catch (IOException ex) {
            Logger.getLogger(Urunler1.class.getName()).log(Level.SEVERE, null, ex);
        }

            temp= siparisIstekleri.get(0).split(";");        
            urunSepet1.setText(temp[4]+" nolu müşterinin siparişi toplam  =  "+temp[3]+" TL");

            
            temp1= siparisIstekleri.get(1).split(";");
            urunSepet2.setText(temp1[4]+" nolu müşterinin siparişi toplam  =  "+temp1[3]+" TL");
            
        
           
            temp2= siparisIstekleri.get(2).split(";");
            urunSepet3.setText(temp2[4]+" nolu müşterinin siparişi toplam  =  "+temp2[4]+" TL");
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NYPODEV.siparisler.setVisible(false);
        NYPODEV.onaylananSiparisler.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            
            BufferedWriter writer = new BufferedWriter(new FileWriter("/Users/beyzanursaritas/Downloads/proje/Siparisler.txt", true));     //
            writer.newLine();
            writer.append(siparisno);
            writer.append(";");                                                       
            writer.append(temp[0]);
            writer.append(";"); 
            writer.append(temp[1]);
            writer.append(";");                                                       
            writer.append(temp[2]);
            writer.append(";");
            writer.append(temp[3]);
            writer.append(";");
            writer.append(temp[4]);
            writer.append(";");                                                       
            
            writer.flush();  //sifon çekmek gibi yazdığın metinleri txt ye yolluyor 
            siparisno+=1;
            JOptionPane.showMessageDialog(null,"Sipariş başarıyla onaylanmıştır.");

        }catch (FileNotFoundException ex) {
           
        } catch (IOException ex) {
             Logger.getLogger(siparisler.class.getName()).log(Level.SEVERE, null, ex);
         }
        urunSepet1.setText(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
              try {
            
            BufferedWriter writer = new BufferedWriter(new FileWriter("/Users/beyzanursaritas/Downloads/proje/Siparisler.txt", true));     //
            writer.newLine();
            writer.append(siparisno);
            writer.append(";");                                                       
            writer.append(temp1[0]);
            writer.append(";"); 
            writer.append(temp1[1]);
            writer.append(";");                                                       
            writer.append(temp1[2]);
            writer.append(";");
            writer.append(temp1[3]);
            writer.append(";");
            writer.append(temp1[4]);
            writer.append(";");                                                       
            
            writer.flush();  //sifon çekmek gibi yazdığın metinleri txt ye yolluyor 
            siparisno+=1;
            JOptionPane.showMessageDialog(null,"Sipariş başarıyla onaylanmıştır.");

        }catch (FileNotFoundException ex) {
           
        } catch (IOException ex) {
             Logger.getLogger(siparisler.class.getName()).log(Level.SEVERE, null, ex);
         }
        urunSepet2.setText(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
              try {
            
            BufferedWriter writer = new BufferedWriter(new FileWriter("/Users/beyzanursaritas/Downloads/proje/Siparisler.txt", true));     //
            writer.newLine();
            writer.append(siparisno);
            writer.append(";");                                                       
            writer.append(temp2[0]);
            writer.append(";"); 
            writer.append(temp2[1]);
            writer.append(";");                                                       
            writer.append(temp2[2]);
            writer.append(";");
            writer.append(temp2[3]);
            writer.append(";");
            writer.append(temp2[4]);
            writer.append(";");                                                       
            
            writer.flush();  //sifon çekmek gibi yazdığın metinleri txt ye yolluyor 
            siparisno+=1;
            JOptionPane.showMessageDialog(null,"Sipariş başarıyla onaylanmıştır.");

        }catch (FileNotFoundException ex) {
           
        } catch (IOException ex) {
             Logger.getLogger(siparisler.class.getName()).log(Level.SEVERE, null, ex);
         }
        urunSepet3.setText(null);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        NYPODEV.siparisler.setVisible(false);
        NYPODEV.urunlerYetkili.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField urunSepet1;
    private javax.swing.JTextField urunSepet2;
    private javax.swing.JTextField urunSepet3;
    // End of variables declaration//GEN-END:variables
}
