/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nypodev;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static nypodev.NYPODEV.calisanGiris;
import static nypodev.NYPODEV.siparisler;
import static nypodev.NYPODEV.urunlerYetkili;
import static nypodev.Urun.k;
import static nypodev.Urun.urunler;
//import static nypodev.Urunler1.gecici;
import static nypodev.urunlerYetkili.urunBul;


/**
 *
 * @author DELL
 */
public class urunlerYetkili extends javax.swing.JFrame {
    static String urunBul;
    public static String a;
    public static String b;
    public static String c;
    public String temp[];
    public String temp1[];
    public String temp2[];
    int node0,node1,node2;
    
    
    File f = new File("/Users/beyzanursaritas/Downloads/proje/Urun.txt");
 
    public urunlerYetkili() {
        initComponents();
    }
    public  void main(String[] args) {

        int i;
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(f))); // txt'den okuma yapmak için gereken kod.
        } catch (FileNotFoundException ex) {
            Logger.getLogger(urunlerYetkili.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
        try {
            while((k = reader.readLine()) != null ){                                                          // txt içindeki veriyi kullanicilar adlı bir arrayList içine ekliyor.
                urunler.add(k);
            }
        } catch (IOException ex) {
            Logger.getLogger(urunlerYetkili.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
     
       
    /**
     * Creates new form Urunler1
     */
  
   
                                    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        aramaBlogu = new javax.swing.JTextField();
        ara = new javax.swing.JButton();
        urun1 = new javax.swing.JTextField();
        urun2 = new javax.swing.JTextField();
        urun3 = new javax.swing.JTextField();
        ekle1 = new javax.swing.JButton();
        ekle2 = new javax.swing.JButton();
        ekle3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        urunGoster = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün ara");

        aramaBlogu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aramaBloguActionPerformed(evt);
            }
        });

        ara.setText("Ara");
        ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                araActionPerformed(evt);
            }
        });

        urun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urun1ActionPerformed(evt);
            }
        });

        ekle1.setText("Güncelle");
        ekle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle1ActionPerformed(evt);
            }
        });

        ekle2.setText("Güncelle");
        ekle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle2ActionPerformed(evt);
            }
        });

        ekle3.setText("Güncelle");
        ekle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle3ActionPerformed(evt);
            }
        });

        jButton5.setText("Geri");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Siparişler");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        urunGoster.setText("Ürünleri Göster");
        urunGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunGosterActionPerformed(evt);
            }
        });

        jButton7.setText("Tedarikçiler");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(urun3)
                                    .addComponent(urun2)
                                    .addComponent(urun1)
                                    .addComponent(aramaBlogu)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(urunGoster)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton6)
                                    .addComponent(ara)
                                    .addComponent(ekle1)
                                    .addComponent(ekle2)
                                    .addComponent(ekle3)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton7)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(urunGoster))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aramaBlogu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ara))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urun2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urun3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_araActionPerformed
        // TODO add your handling code here:
        urun1.setText(null);
        urun2.setText(null);
        urun3.setText(null);
        int i;
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(f))); // txt'den okuma yapmak için gereken kod.
        } catch (FileNotFoundException ex) {
            Logger.getLogger(urunlerYetkili.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            while((k = reader.readLine()) != null ){                                                          // txt içindeki veriyi kullanicilar adlı bir arrayList içine ekliyor.
                urunler.add(k);
            }
        } catch (IOException ex) {
            Logger.getLogger(urunlerYetkili.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        for(i = 0 ; i<urunler.size() ; i++){
        String temp[] = urunler.get(i).split(";");    
            if(aramaBlogu.getText().equalsIgnoreCase(temp[1])){
                String urunFiyat = temp[1]+"  =  "+temp[2]+" TL";
                urun1.setText(urunFiyat);  //yazdırma
            }
        }
        
        
    }//GEN-LAST:event_araActionPerformed
  
      
    
    private void aramaBloguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aramaBloguActionPerformed
        // TODO add your handling code here:
        urunBul = String.valueOf(aramaBlogu.getText());
    }//GEN-LAST:event_aramaBloguActionPerformed
    
    private void urun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urun1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_urun1ActionPerformed

    private void urunGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunGosterActionPerformed
    node0=0;
    node1=1;
    node2=2;
        int i;
        BufferedReader reader = null;
        try {
            reader = new BufferedReader(new InputStreamReader(new FileInputStream(f))); // txt'den okuma yapmak için gereken kod.
        } catch (FileNotFoundException ex) {
            Logger.getLogger(urunlerYetkili.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            while((k = reader.readLine()) != null ){                                                          // txt içindeki veriyi kullanicilar adlı bir arrayList içine ekliyor.
                urunler.add(k);
            }
        } catch (IOException ex) {
            Logger.getLogger(urunlerYetkili.class.getName()).log(Level.SEVERE, null, ex);
        }

            temp = urunler.get(node0).split(";");        
            urun1.setText(temp[1]+"  =  "+temp[3]+" adet stokta var.");

            
            temp1 = urunler.get(node1).split(";");
            urun2.setText(temp1[1]+"  =  "+temp1[3]+" adet stokta var.");
            
        
           
            temp2 = urunler.get(node2).split(";");
            urun3.setText(temp2[1]+"  =  "+temp2[3]+" adet stokta var.");
            
    }//GEN-LAST:event_urunGosterActionPerformed

    private void ekle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle1ActionPerformed
        // TODO add your handling code here:
       temp[3]=urun1.getText();
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("/Users/beyzanursaritas/Downloads/proje/Urun.txt", true));     //
            writer.newLine();
            writer.append(temp[0]);
            writer.append(";");                                                       
            writer.append(temp[1]);
            writer.append(";"); 
            writer.append(temp[2]);
            writer.append(";");                                                       
            writer.append(temp[3]);
            writer.append(";");
            writer.append(temp[4]);
            
            
            writer.flush();
            node0+=1;
            JOptionPane.showMessageDialog(null,"Stok başarıyla güncellendi.");

        }catch (FileNotFoundException ex) {
           
        } catch (IOException ex) {
            Logger.getLogger(urunlerYetkili.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        

    }//GEN-LAST:event_ekle1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        urunlerYetkili.setVisible(false);
        siparisler.setVisible(true);
        
    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        urunlerYetkili.setVisible(false);
        calisanGiris.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ekle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle2ActionPerformed
        // TODO add your handling code here:
        temp1[3]=urun1.getText();
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("/Users/beyzanursaritas/Downloads/proje/Urun.txt", true));     //
            writer.newLine();
            writer.append(temp1[0]);
            writer.append(";");                                                       
            writer.append(temp1[1]);
            writer.append(";"); 
            writer.append(temp1[2]);
            writer.append(";");                                                       
            writer.append(temp1[3]);
            writer.append(";");
            writer.append(temp1[4]);
            
            
            writer.flush();
            node1+=1;
            JOptionPane.showMessageDialog(null,"Stok başarıyla güncellendi.");

        }catch (FileNotFoundException ex) {
           
        } catch (IOException ex) {
            Logger.getLogger(urunlerYetkili.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ekle2ActionPerformed

    private void ekle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle3ActionPerformed
temp2[3]=urun3.getText();
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("/Users/beyzanursaritas/Downloads/proje/Urun.txt", true));     //
            writer.newLine();
            writer.append(temp2[0]);
            writer.append(";");                                                       
            writer.append(temp2[1]);
            writer.append(";"); 
            writer.append(temp2[2]);
            writer.append(";");                                                       
            writer.append(temp2[3]);
            writer.append(";");
            writer.append(temp2[4]);
            
            
            writer.flush();
            node2+=1;
            JOptionPane.showMessageDialog(null,"Stok başarıyla güncellendi.");

        }catch (FileNotFoundException ex) {
           
        } catch (IOException ex) {
            Logger.getLogger(urunlerYetkili.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_ekle3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       NYPODEV.urunlerYetkili.setVisible(false);
       NYPODEV.tedarikciler.setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed
    
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ara;
    private javax.swing.JTextField aramaBlogu;
    private javax.swing.JButton ekle1;
    private javax.swing.JButton ekle2;
    private javax.swing.JButton ekle3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField urun1;
    private javax.swing.JTextField urun2;
    private javax.swing.JTextField urun3;
    private javax.swing.JButton urunGoster;
    // End of variables declaration//GEN-END:variables
}
